export default {
  response: {
    orders: [
      {
        order_id: '386615037164257301',
        status: '1024',
        revision: '1',
        create_time: '1639970119630',
        update_time: '1639970160349',
        delete_time: '0',
        group_id: '386204470670786584',
        station_id: '386204472616943642',
        creator_id: '386204473069928473',
        bill_customer_id: '386204474378551323',
        receive_customer_id: '386204474378551323',
        driver_id: '0',
        service_period_id: '386204474093338653',
        quotation_id: '386204472684052523',
        customer_type: 0,
        addresses: {
          addresses: [
            {
              country_id: '0',
              province_id: '0',
              city_id: '4403',
              district_id: '440305',
              street_id: '440305007',
              receiver: '李大姐',
              phone: '87654321',
              address: '羊肠小道',
              poi_title: '',
              poi_address: '',
              company_name: '',
              geotag: {
                latitude: '113.943511',
                longitude: '22.548308',
              },
              is_default: false,
            },
          ],
        },
        service_period: {
          service_period_id: '386204474093338653',
          revision: '1',
          create_time: '1639725404892',
          update_time: '1639725404892',
          delete_time: '0',
          group_id: '386204470670786584',
          menu_period_group_id: '0',
          name: '不限档',
          description: 'ServicePeriod for testing',
          type: 0,
          order_create_min_time: '0',
          order_create_max_time: '86399999',
          order_receive_min_time: '82800000',
          order_receive_max_time: '104400000',
          order_receive_min_date: '0',
          order_receive_max_date: '7',
          default_receive_time: '0',
          default_receive_date: '0',
        },
        menu_id: '0',
        menu_period_group_id: '0',
        updater_id: '0',
        menu_detail_id: '0',
        quotation_type: 1,
        supplier_id: '0',
        purchaser_id: '0',
        order_price: '135.42',
        freight_price: '',
        aftersale_price: '',
        outstock_price: '135.42',
        coupon_price: '',
        manual_adjust_price: '',
        sale_price: '135.42',
        sale_price_no_tax: '131.48',
        order_aftersale_price: '',
        detail_aftersale_price: '',
        detail_sum_sale_price: '135.42',
        detail_sum_sale_price_no_tax: '131.48',
        detail_sum_tax_price: '3.94',
        order_price_no_tax: '',
        paid_amount: '',
        refund_amount: '',
        actual_amount: '',
        receive_time: '1640012400000',
        outstock_time: '0',
        order_time: '1639970119474',
        received_time: '0',
        time_zone: 'Asia/Shanghai',
        serial_no: 'DD21122000001',
        state: 1,
        pay_state: 1,
        has_after_sale: false,
        sorting_remark: '',
        sorting_num: '',
        delivery_info: {
          images: [],
        },
        order_type: 3,
        creator_id_type: 2,
        remark: '',
        app_type: 1,
        sorting_info: {
          total_count: 1,
          weight_count: 0,
          out_stock_count: 0,
          unweight_count: 1,
        },
        order_op: 1,
        updater_id_type: 2,
        dining_count: '0',
        customer_additional_info: {
          customer_signature: [],
        },
        settle_sheet_id: '0',
        city_id: '4403',
        district_id: '440305',
        street_id: '440305007',
        customer_id_l1: '386204474160447515',
        customer_id_l2: '0',
        customer_id_l3: '0',
        customer_id_l4: '0',
        customer_id_l5: '0',
        supplier_cooperate_model_type: 1,
        detail_length: '1',
        raw_detail_length: '1',
        detail_category_length: '1',
        order_raw_details: {
          order_details: [
            {
              order_detail_id: '386615037164257302',
              status: '0',
              revision: '0',
              create_time: '1639970119645',
              update_time: '1639970119645',
              delete_time: '0',
              type: 1,
              group_id: '386204470670786584',
              order_id: '386615037164257301',
              sku_id: '386204477079683114',
              bom_id: '0',
              bom_revision: '0',
              sorting_operater_id: '0',
              station_id: '386204472616943642',
              order_unit_value: {
                input: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
              },
              outstock_unit_value: {
                input: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
              },
              sorting_quantity: {
                input: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '0',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '0',
                },
              },
              order_unit_value_v2: {
                quantity: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '111',
                },
                price: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '1.22',
                },
              },
              outstock_unit_value_v2: {
                quantity: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '111',
                },
                price: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '1.22',
                },
              },
              receive_unit_value_v2: {},
              plan_unit_value_v2: {},
              order_unit_value_tax_v2: {},
              order_price: '135.42',
              aftersale_price: '',
              outstock_price: '135.42',
              manual_adjust_price: '',
              sale_price: '135.42',
              sale_price_no_tax: '131.48',
              tax_price: '3.94',
              order_price_no_tax: '',
              up_relation: {
                relations: [],
              },
              down_relation: {
                relations: [],
              },
              unit_cal_info: {
                unit_lists: [
                  {
                    unit_id: '500000',
                    status: '0',
                    revision: '1637668089589',
                    create_time: '1637668089589',
                    update_time: '1637668089589',
                    delete_time: '0',
                    group_id: '0',
                    name: '公斤',
                    rate: '1000',
                    type: 4,
                    parent_id: '500002',
                    country_id: '0',
                  },
                  {
                    unit_id: '500001',
                    status: '0',
                    revision: '1637668089589',
                    create_time: '1637668089589',
                    update_time: '1637668089589',
                    delete_time: '0',
                    group_id: '0',
                    name: '斤',
                    rate: '500',
                    type: 4,
                    parent_id: '500002',
                    country_id: '0',
                  },
                  {
                    unit_id: '102',
                    status: '0',
                    revision: '0',
                    create_time: '0',
                    update_time: '0',
                    delete_time: '0',
                    group_id: '0',
                    name: '袋',
                    rate: '3',
                    type: 0,
                    parent_id: '500001',
                    country_id: '0',
                  },
                ],
              },
              remark: '',
              sorting_status: 1,
              sorting_version: '0',
              address_num: '0',
              sort_num: '1',
              sync_flag: 0,
              sku_is_weight: false,
              sku_unit_is_current_price: false,
              state: 0,
              return_refund_value: {},
              just_refund_value: {},
              sku_is_combine_sku: false,
              accept_value: {},
              supplier_cooperate_model_type: 1,
              manufacture_date: '0',
              purchase_task_id: '0',
              purchase_task_serial_no: '',
              unit_id: '102',
              sku_revision: '1639816624342',
              tax: '3',
              fee_unit_id: '102',
              measure_unit_id: '500001',
              category1_id: '382770389035515946',
              ingredients: {
                ingredients: [],
              },
              sku_name: '大白菜',
              sku_customize_code: '1111',
              sku_loss_ratio: '0',
              receive_customer_id: '0',
              raw_detail_id: '0',
              manual_purchase: false,
              purchase_requisition_id: '0',
              purchase_requisition_detail_id: '0',
            },
          ],
        },
        order_details: {
          order_details: [
            {
              order_detail_id: '386615037181034518',
              status: '0',
              revision: '0',
              create_time: '1639970119652',
              update_time: '1639970119652',
              delete_time: '0',
              type: 2,
              group_id: '386204470670786584',
              order_id: '386615037164257301',
              sku_id: '386204477079683114',
              bom_id: '0',
              bom_revision: '0',
              sorting_operater_id: '0',
              station_id: '386204472616943642',
              order_unit_value: {
                input: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
              },
              outstock_unit_value: {
                input: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '111',
                  price: '1.22',
                  val: '',
                },
              },
              sorting_quantity: {
                input: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '0',
                },
                calculate: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '0',
                },
              },
              order_unit_value_v2: {
                quantity: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '111',
                },
                price: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '1.22',
                },
              },
              outstock_unit_value_v2: {
                quantity: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '111',
                },
                price: {
                  unit_id: '102',
                  quantity: '',
                  price: '',
                  val: '1.22',
                },
              },
              receive_unit_value_v2: {},
              plan_unit_value_v2: {},
              order_unit_value_tax_v2: {},
              order_price: '135.42',
              aftersale_price: '',
              outstock_price: '135.42',
              manual_adjust_price: '',
              sale_price: '135.42',
              sale_price_no_tax: '131.48',
              tax_price: '3.94',
              order_price_no_tax: '',
              up_relation: {
                relations: [],
              },
              down_relation: {
                relations: [],
              },
              unit_cal_info: {
                unit_lists: [
                  {
                    unit_id: '500000',
                    status: '0',
                    revision: '1637668089589',
                    create_time: '1637668089589',
                    update_time: '1637668089589',
                    delete_time: '0',
                    group_id: '0',
                    name: '公斤',
                    rate: '1000',
                    type: 4,
                    parent_id: '500002',
                    country_id: '0',
                  },
                  {
                    unit_id: '500001',
                    status: '0',
                    revision: '1637668089589',
                    create_time: '1637668089589',
                    update_time: '1637668089589',
                    delete_time: '0',
                    group_id: '0',
                    name: '斤',
                    rate: '500',
                    type: 4,
                    parent_id: '500002',
                    country_id: '0',
                  },
                  {
                    unit_id: '102',
                    status: '0',
                    revision: '0',
                    create_time: '0',
                    update_time: '0',
                    delete_time: '0',
                    group_id: '0',
                    name: '袋',
                    rate: '3',
                    type: 0,
                    parent_id: '500001',
                    country_id: '0',
                  },
                ],
              },
              remark: '',
              sorting_status: 1,
              sorting_version: '0',
              address_num: '0',
              sort_num: '1',
              sync_flag: 0,
              sku_is_weight: false,
              sku_unit_is_current_price: false,
              state: 0,
              return_refund_value: {},
              just_refund_value: {},
              sku_is_combine_sku: false,
              accept_value: {},
              supplier_cooperate_model_type: 1,
              manufacture_date: '0',
              purchase_task_id: '0',
              purchase_task_serial_no: '',
              unit_id: '102',
              sku_revision: '1639816624342',
              tax: '3',
              fee_unit_id: '102',
              measure_unit_id: '500001',
              category1_id: '382770389035515946',
              ingredients: {
                ingredients: [],
              },
              sku_name: '大白菜',
              sku_customize_code: '1111',
              sku_loss_ratio: '0',
              receive_customer_id: '0',
              raw_detail_id: '0',
              manual_purchase: false,
              purchase_requisition_id: '0',
              purchase_requisition_detail_id: '0',
            },
          ],
        },
      },
    ],
    relation_info: {
      customers: {
        '386204474378551323': {
          customer_id: '386204474378551323',
          status: '512',
          create_time: '1639725405061',
          update_time: '1639725405061',
          delete_time: '0',
          group_id: '386204470670786584',
          parent_id: '386204474160447515',
          create_group_user_id: '386204473069928473',
          sales_group_user_id: '386204473069928473',
          bound_station_id: '0',
          name: '【测试】大猪蹄子一号餐厅',
          remark: '',
          customized_code: 'DZTZ01',
          type: 2,
          is_reviewed: true,
          is_in_whitelist: false,
          is_frozen: false,
          level: 2,
          child_number: '0',
          settlement: {
            weekly_or_monthly_credit_start_day: 0,
            weekly_or_monthly_credit_settle_day: 0,
            customized_credit_start_time: 0,
            customized_credit_proied_days: 0,
            customized_credit_deley_days: 0,
            china_vat_invoice: {
              company_name: '',
              company_address: '',
              company_phone: '',
              invoice_type: 2,
              taxpayer_identity_number: '',
              bank_name: '',
              bank_account: '',
              bank_card_owner_name: '',
              max_invoice_amount: '',
              business_license_number: '',
              financial_contact_name: '',
              financial_contact_phone: '',
              taxpayer_type: 0,
            },
          },
          settlement_method: 0,
          credit_type: 5,
          phone: '1234567',
          gender: 0,
          parent_phone: '',
          parent_name: '【测试】唐老鸭',
          city_id: '4403',
          district_id: '440305',
          street_id: '440305007',
          relation_group_id: '0',
          relation_supplier_id: '0',
          inquiry_time: '0',
          attrs: {
            addresses: [
              {
                country_id: '0',
                province_id: '0',
                city_id: '4403',
                district_id: '440305',
                street_id: '440305007',
                receiver: '李大姐',
                phone: '87654321',
                address: '羊肠小道',
                poi_title: '',
                poi_address: '',
                company_name: '',
                geotag: {
                  latitude: '113.943511',
                  longitude: '22.548308',
                },
                is_default: false,
              },
            ],
            parent_ids: ['386204474160447515'],
            children_number: 0,
            menu_period_relation: {},
            last_menu_period_order_recv_time: {},
            dining_calendar: false,
          },
          school_type: 0,
          wait_pay_amount: '',
        },
        '386204474160447515': {
          customer_id: '386204474160447515',
          status: '256',
          create_time: '1639725404933',
          update_time: '1639725405058',
          delete_time: '0',
          group_id: '386204470670786584',
          parent_id: '0',
          create_group_user_id: '386204473069928473',
          sales_group_user_id: '386204473069928473',
          bound_station_id: '0',
          name: '【测试】大猪蹄子餐饮集团',
          remark: '',
          customized_code: 'DZTZ',
          type: 2,
          is_reviewed: true,
          is_in_whitelist: false,
          is_frozen: false,
          level: 1,
          child_number: '1',
          settlement: {
            weekly_or_monthly_credit_start_day: 0,
            weekly_or_monthly_credit_settle_day: 0,
            customized_credit_start_time: 0,
            customized_credit_proied_days: 0,
            customized_credit_deley_days: 0,
            china_vat_invoice: {
              company_name: '',
              company_address: '',
              company_phone: '',
              invoice_type: 2,
              taxpayer_identity_number: '',
              bank_name: '',
              bank_account: '',
              bank_card_owner_name: '',
              max_invoice_amount: '',
              business_license_number: '',
              financial_contact_name: '蹄子',
              financial_contact_phone: '131223',
              taxpayer_type: 0,
            },
          },
          settlement_method: 0,
          credit_type: 5,
          phone: '1234567',
          gender: 0,
          parent_phone: '',
          parent_name: '',
          city_id: '4403',
          district_id: '440305',
          street_id: '440305007',
          relation_group_id: '0',
          relation_supplier_id: '0',
          inquiry_time: '0',
          attrs: {
            addresses: [
              {
                country_id: '0',
                province_id: '0',
                city_id: '4403',
                district_id: '440305',
                street_id: '440305007',
                receiver: '张大头',
                phone: '1234567',
                address: '雀巢街道',
                poi_title: '',
                poi_address: '',
                company_name: '',
                geotag: {
                  latitude: '113.943511',
                  longitude: '22.5484',
                },
                is_default: false,
              },
            ],
            parent_ids: [],
            children_number: 0,
            menu_period_relation: {},
            last_menu_period_order_recv_time: {},
            dining_calendar: false,
          },
          school_type: 0,
          wait_pay_amount: '',
        },
      },
      quotations: {
        '386204472684052523': {
          quotation_id: '386204472684052523',
          revision: '0',
          create_time: '1639725404064',
          update_time: '1639725404064',
          delete_time: '0',
          group_id: '386204470670786584',
          station_id: '386204472616943642',
          creator_id: '0',
          parent_id: '0',
          inner_name: '默认报价单',
          outer_name: '默认报价单',
          description: '默认报价单',
          is_default: true,
          type: 1,
          avail_menu_period_groups: {
            menu_period_group_ids: [],
          },
          update_valid_time: {
            start_day: '0',
            start_time: '0',
            cycle_type: 0,
          },
          sku_count: '0',
          customer_count: '0',
          customer_type: 0,
          start_time: '0',
          end_time: '0',
          status: 2,
          supplier_id: '0',
          serial_no: 'BJD21121700001',
          remark: '',
          purchase_user_id: '0',
        },
      },
      sku_snaps: {
        '386204477079683114_1639816624342': {
          sku_id: '386204477079683114',
          status: '0',
          revision: '1639816624342',
          create_time: '1639725406677',
          update_time: '1639816624342',
          delete_time: '0',
          group_id: '386204470670786584',
          category_id: '382770389035515948',
          category1_id: '382770389035515946',
          category2_id: '382770389035515948',
          category3_id: '0',
          category4_id: '0',
          category5_id: '0',
          spu_id: '386204476140159017',
          base_unit_id: '500000',
          second_base_unit_id: '0',
          second_base_unit_ratio: '',
          max_unit_id: '102',
          source_sku_id: '0',
          source_group_id: '0',
          name: '大白菜',
          customize_code: '1111',
          desc: '',
          sku_type: 2,
          not_package_sub_sku_type: 1,
          package_sub_sku_type: 0,
          expiry_date: 0,
          repeated_field: {
            alias: [],
            images: [],
            extras: [],
          },
          dispatch_type: 1,
          rank: 0,
          purchaser_id: '386204473069928473',
          supplier_id: '0',
          production_unit_id: '0',
          purchase_unit_id: '101',
          purchase_spec_id: '0',
          loss_ratio: '0',
          package_price: '',
          tax: '3',
          finance_category_id: '0',
          input_tax: '0',
          supplier_input_taxs: {
            supplier_input_tax: {},
          },
          manual_purchase: false,
          shelf_id: '0',
          units: {
            units: [
              {
                unit_id: '101',
                status: '0',
                revision: '0',
                create_time: '0',
                update_time: '0',
                delete_time: '0',
                group_id: '0',
                name: '包',
                rate: '3',
                type: 0,
                parent_id: '500000',
                country_id: '0',
              },
              {
                unit_id: '102',
                status: '0',
                revision: '0',
                create_time: '0',
                update_time: '0',
                delete_time: '0',
                group_id: '0',
                name: '袋',
                rate: '3',
                type: 0,
                parent_id: '500001',
                country_id: '0',
              },
            ],
          },
          on_sale: true,
          is_weight: false,
          has_image: false,
          ingredients: {
            ingredients: [],
          },
          related_combine_sku_ids_map: {
            related_combine_sku_ids_map: {},
          },
          package_calculate_type: 0,
          package_num: 0,
          package_sku_id: '0',
          cost: '',
          min_price: '',
          max_price: '',
          supplier_cooperate_model_type: 1,
          sku_hot: '0',
          sku_order_count: '0',
        },
      },
      group_users: {
        '386204473069928473': {
          group_user_id: '386204473069928473',
          status: '0',
          create_time: '1639725404283',
          update_time: '1639725404283',
          delete_time: '0',
          group_id: '386204470670786584',
          account_id: '386204472918933505',
          distribution_contractor_id: '0',
          name: 'admin',
          is_valid: true,
          type: 8,
          attrs: {
            visable_all_stations: false,
            visable_station_ids: [],
            permission_ids: [],
            bounded_customer_ids: [],
            distribution_contractor_ids: [],
            car_license_plate_number: '',
            id_number: '',
          },
          remark: '',
          username: 'admin',
          phone: '12312341234',
          email: '',
        },
      },
      customer_users: {},
      customer_label_relation: {
        '386204474160447515': {
          values: ['386204474110115885'],
        },
        '386204474378551323': {
          values: ['386204474143670317'],
        },
      },
      menu_period_groups: {},
      customer_label: {
        '386204474110115885': {
          customer_label_id: '386204474110115885',
          revision: '0',
          create_time: '1639725404901',
          update_time: '1639725404901',
          delete_time: '0',
          group_id: '386204470670786584',
          name: 'customer_label1',
        },
        '386204474143670317': {
          customer_label_id: '386204474143670317',
          revision: '0',
          create_time: '1639725404922',
          update_time: '1639725404922',
          delete_time: '0',
          group_id: '386204470670786584',
          name: 'customer_label2',
        },
      },
      category: {
        '382770389035515946': {
          category_id: '382770389035515946',
          status: '0',
          revision: '0',
          create_time: '1639725406055',
          update_time: '1639725406055',
          delete_time: '0',
          group_id: '386204470670786584',
          parent_id: '0',
          source_category_id: '0',
          source_group_id: '0',
          name: '蔬菜',
          icon: '',
          rank: 0,
          level: 1,
        },
      },
      single_ssu_infos: [],
    },
    total_order_price: '0',
    total_outstock_price: '0',
    sorting_finish_count: 0,
    sorting_unfinish_count: 0,
    paging: {
      has_more: false,
      count: 0,
    },
  },
  relation: {
    customer_routes: {},
    routes: {},
  },
  paging: {
    has_more: false,
    count: 0,
  },
}
